// <auto-generated />
namespace East2West.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class inittable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inittable));
        
        string IMigrationMetadata.Id
        {
            get { return "202206290409178_init-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
