// <auto-generated />
namespace East2West.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatemodeluser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatemodeluser));
        
        string IMigrationMetadata.Id
        {
            get { return "202206230256582_update-model-user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
