// <auto-generated />
namespace East2West.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updatetablename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatetablename));
        
        string IMigrationMetadata.Id
        {
            get { return "202206171514458_update-table-name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
