// <auto-generated />
namespace East2West.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_database2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_database2));
        
        string IMigrationMetadata.Id
        {
            get { return "202206291417517_update_database2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
